---
# tasks file for environmrnt-setup

- name: sudo Update apt repository cache
  apt:
    update_cache: yes

- name: Install necessary packages
  apt:
    name:
      - python3
      - python3-pip
      - git
    state: present
